---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Paris"
    labels:
      - "actions"
      - "dependencies"
    assignees:
      - "Pandemonium1986"
    # commit-message:
    #   prefix: "dependabot-action"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Paris"
    labels:
      - "docker"
      - "dependencies"
    assignees:
      - "Pandemonium1986"
    # commit-message:
    #   prefix: "dependabot-docker"
