---
name: "Docker Workflow"

on:
  schedule:
    - cron: "0 8 * * *"
  push:
    branches:
      - main
      - develop
    tags:
      - "*"
  workflow_dispatch:

env:
  DOCKER_USER: "pandemonium1986"
  DOCKER_IMAGE: "centos7"

jobs:
  called-linter:
    permissions:
      contents: read
      packages: read
      statuses: write
    name: "Called: GitHub Super Linter Workflow"
    uses: pandemonium1986/.github/.github/workflows/called-linter.yml@main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
  called-docker:
    permissions:
      contents: read
      packages: write
      statuses: write
    name: "Called: Docker Build and Push Workflow"
    uses: pandemonium1986/.github/.github/workflows/called-docker.yml@develop
    with:
      docker-user: "pandemonium1986"
      docker-image: "centos7"
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

